export const techDisplayNames: Record<string, string> = {
  aarch64: "AArch64",
  adonisjs: "AdonisJS",
  aerospike: "Aerospike",
  aframe: "A-Frame",
  aftereffects: "After Effects",
  akka: "Akka",
  algolia: "Algolia",
  almalinux: "AlmaLinux",
  alpinejs: "Alpine.js",
  amazonwebservices: "Amazon Web Services",
  anaconda: "Anaconda",
  android: "Android",
  androidstudio: "Android Studio",
  angular: "Angular",
  angularjs: "AngularJS",
  angularmaterial: "Angular Material",
  ansible: "Ansible",
  ansys: "ANSYS",
  antdesign: "Ant Design",
  apache: "Apache",
  apacheairflow: "Apache Airflow",
  apachekafka: "Apache Kafka",
  apachespark: "Apache Spark",
  apex: "Apex",
  apl: "APL",
  apollographql: "Apollo GraphQL",
  appcelerator: "Appcelerator",
  apple: "Apple",
  appwrite: "Appwrite",
  archlinux: "Arch Linux",
  arduino: "Arduino",
  argocd: "Argo CD",
  artixlinux: "Artix Linux",
  astro: "Astro",
  atom: "Atom",
  awk: "AWK",
  axios: "Axios",
  azure: "Microsoft Azure",
  azuredevops: "Azure DevOps",
  azuresqldatabase: "Azure SQL Database",
  babel: "Babel",
  babylonjs: "Babylon.js",
  backbonejs: "Backbone.js",
  bash: "Bash",
  bazel: "Bazel",
  bitbucket: "Bitbucket",
  blender: "Blender",
  bootstrap: "Bootstrap",
  bulma: "Bulma",
  bun: "Bun",
  c: "C",
  cplusplus: "C++",
  csharp: "C#",
  css3: "CSS3",
  dart: "Dart",
  datadog: "Datadog",
  debian: "Debian",
  denojs: "Deno",
  digitalocean: "DigitalOcean",
  discordjs: "Discord.js",
  django: "Django",
  djangorest: "Django REST Framework",
  docker: "Docker",
  dotnetcore: ".NET Core",
  drupal: "Drupal",
  duckdb: "DuckDB",
  dynamodb: "DynamoDB",
  eclipse: "Eclipse",
  elasticsearch: "Elasticsearch",
  electron: "Electron",
  elixir: "Elixir",
  emacs: "Emacs",
  ember: "Ember.js",
  envoy: "Envoy",
  erlang: "Erlang",
  eslint: "ESLint",
  expo: "Expo",
  express: "Express.js",
  facebook: "Facebook",
  fastapi: "FastAPI",
  fastify: "Fastify",
  figma: "Figma",
  firebase: "Firebase",
  flask: "Flask",
  flutter: "Flutter",
  fortran: "Fortran",
  framermotion: "Framer Motion",
  gatsby: "Gatsby",
  gcc: "GCC",
  git: "Git",
  github: "GitHub",
  gitlab: "GitLab",
  go: "Go",
  godot: "Godot Engine",
  google: "Google",
  googlecloud: "Google Cloud",
  gradle: "Gradle",
  grafana: "Grafana",
  graphql: "GraphQL",
  grpc: "gRPC",
  gulp: "Gulp",
  haskell: "Haskell",
  helm: "Helm",
  heroku: "Heroku",
  hibernate: "Hibernate",
  html5: "HTML5",
  hugo: "Hugo",
  illustrator: "Adobe Illustrator",
  intellij: "IntelliJ IDEA",
  ionic: "Ionic",
  java: "Java",
  javascript: "JavaScript",
  jenkins: "Jenkins",
  jest: "Jest",
  jira: "Jira",
  jquery: "jQuery",
  json: "JSON",
  julia: "Julia",
  jupyter: "Jupyter",
  kafka: "Kafka",
  keras: "Keras",
  kibana: "Kibana",
  kotlin: "Kotlin",
  kubernetes: "Kubernetes",
  laravel: "Laravel",
  latex: "LaTeX",
  linux: "Linux",
  lua: "Lua",
  magento: "Magento",
  mariadb: "MariaDB",
  markdown: "Markdown",
  materialui: "Material UI",
  matplotlib: "Matplotlib",
  maven: "Maven",
  mongodb: "MongoDB",
  mongoose: "Mongoose",
  mysql: "MySQL",
  neo4j: "Neo4j",
  nestjs: "NestJS",
  netlify: "Netlify",
  nextjs: "Next.js",
  nginx: "Nginx",
  nodejs: "Node.js",
  npm: "npm",
  numpy: "NumPy",
  nuxtjs: "Nuxt.js",
  objectivec: "Objective-C",
  opencv: "OpenCV",
  opengl: "OpenGL",
  openstack: "OpenStack",
  oracle: "Oracle",
  pandas: "Pandas",
  perl: "Perl",
  photoshop: "Adobe Photoshop",
  php: "PHP",
  phpstorm: "PhpStorm",
  playwright: "Playwright",
  plotly: "Plotly",
  pnpm: "pnpm",
  podman: "Podman",
  postcss: "PostCSS",
  postgresql: "PostgreSQL",
  postman: "Postman",
  powershell: "PowerShell",
  premierepro: "Adobe Premiere Pro",
  prisma: "Prisma",
  prometheus: "Prometheus",
  puppet: "Puppet",
  pycharm: "PyCharm",
  python: "Python",
  pytorch: "PyTorch",
  qt: "Qt",
  quarkus: "Quarkus",
  r: "R",
  rabbitmq: "RabbitMQ",
  rails: "Ruby on Rails",
  raspberrypi: "Raspberry Pi",
  react: "React",
  reactnative: "React Native",
  reactrouter: "React Router",
  redis: "Redis",
  redux: "Redux",
  remix: "Remix",
  ruby: "Ruby",
  rust: "Rust",
  safari: "Safari",
  sass: "Sass",
  scala: "Scala",
  scikitlearn: "scikit-learn",
  selenium: "Selenium",
  sentry: "Sentry",
  spring: "Spring",
  sqlite: "SQLite",
  ssh: "SSH",
  stackoverflow: "Stack Overflow",
  storybook: "Storybook",
  streamlit: "Streamlit",
  styledcomponents: "Styled Components",
  svelte: "Svelte",
  swagger: "Swagger",
  swift: "Swift",
  symfony: "Symfony",
  tailwindcss: "Tailwind CSS",
  tensorflow: "TensorFlow",
  terraform: "Terraform",
  tomcat: "Apache Tomcat",
  travis: "Travis CI",
  trello: "Trello",
  twilio: "Twilio",
  twitter: "Twitter",
  typescript: "TypeScript",
  ubuntu: "Ubuntu",
  unity: "Unity",
  unrealengine: "Unreal Engine",
  vercel: "Vercel",
  vim: "Vim",
  visualstudio: "Visual Studio",
  vite: "Vite",
  vscode: "VS Code",
  vuejs: "Vue.js",
  vuetify: "Vuetify",
  webpack: "Webpack",
  windows11: "Windows 11",
  wordpress: "WordPress",
  xcode: "Xcode",
  xml: "XML",
  yaml: "YAML",
  yarn: "Yarn",
  zsh: "Zsh",
  zustand: "Zustand",
};
